version: '3'
services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /src
    command: /src/docker.sh
    environment:
      - GAE_DIR=/google-cloud-sdk/platform/google_appengine
      - DATASTORE_PATH=/datastore/datastore.db
      - APPENGINE_PROJECT_ID=$APPENGINE_PROJECT_ID
    volumes:
      - .:/src
      - ./.datastore:/datastore
    ports:
      - "9000:9000"
      - "9080:9080"
